FROM stackfeed/alpine-python3
MAINTAINER Denis Baryshev <dennybaa@gmail.com>

RUN apk --no-cache --update add libffi openssl ca-certificates net-tools openvpn bridge-utils \
                                alpine-sdk libffi-dev openssl-dev linux-headers python3-dev

RUN pip install wheel
ADD build.sh /
VOLUME /wheels

CMD ["/bin/sh", "/build.sh"]
