version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: docker:17.10.0-ce-git
      - image: circleci/golang:1.8

    environment:
      VERSION: "1.28.1515.73"
      URL: "https://github.com/pritunl/pritunl/archive/1.28.1515.73.tar.gz"
      CONTAINER: dennybaa/pritunl

    steps:
      - checkout
      - setup_remote_docker
      - run: docker ps -a
      - run: docker run alpine echo hello
      - run: docker ps -a
      # - run: docker build -t build-container -f Dockerfile.build ./

      # - run: |
      #     docker run -it -v $(pwd)/pritunl:/pritunl \
      #                    -v $(pwd)/wheels:/wheels \
      #                    -w /pritunl build-container

      # - run: go get github.com/pritunl/pritunl-dns
      # - run: go get github.com/pritunl/pritunl-web
      # - run: pwd
      # - run: find /home
