version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: docker:17.10.0-ce-git
      # - image: circleci/golang:1.8

    environment:
      VERSION: "1.28.1515.73"
      SOURCE_URL: "https://github.com/pritunl/pritunl/archive/1.28.1515.73.tar.gz"

    steps:
      - checkout
      - setup_remote_docker
      - run: apk --no-cache add ca-certificates openssl && update-ca-certificates

      - run:
          name: Fetch pritunl source
          command: |
            wget $SOURCE_URL
            tar xzf ${VERSION}.tar.gz && mv pritunl-${VERSION} pritunl

      - run:
          name: Python wheels builder container
          command: docker build --tag build-wheels -f Dockerfile.build ./

      - run:
          name: Build pritunl wheels and copy back here (primary machine)
          command: |
            docker create --name data -v /wheels -v /pritunl -v /go alpine:3.6 /bin/true
            docker cp pritunl data:/
            docker run -t --volumes-from data -w /pritunl build-wheels
            docker cp data:/wheels ./

      - run:
          name: Get pritunl dns and web build and copy back
          command: |
            docker run  --name gobuilder \
                        --volumes-from data -d \
                        circleci/golang:1.8 sleep infinity
            docker exec -t gobuilder go get github.com/pritunl/pritunl-dns
            docker exec -t gobuilder go get github.com/pritunl/pritunl-web
            docker cp gobuilder:/go/bin/pritunl-* .
            ls -l

      # - run:
            # docker build -t ${CONTAINER}:alpine -f Dockerfile.alpine .
