version: 2
jobs:
  build:
    docker:
      # CircleCI Go images available at: https://hub.docker.com/r/circleci/golang/
      - image: docker:17.10.0-ce-git
      - image: circleci/golang:1.8

    environment:
      VERSION: "1.28.1515.73"
      URL: "https://github.com/pritunl/pritunl/archive/1.28.1515.73.tar.gz"
      CONTAINER: dennybaa/pritunl

    steps:
      - checkout
      - setup_remote_docker
      - run: docker ps -a
      - run: docker run alpine mount
      - run: docker ps -a
      - run: docker images
      - run: |
          doker build --tag generate-wheels -f Dockerfile.build ./ &
          sleep 2
          ps
          wait $!

      - run: |
          docker images &
          sleep 0.1
          ps

      # - run: docker run -v $(pwd)/README.md:/txt alpine cat /txt
      # - run:
      #     name: A
      #     command: |
      #       docker create -v /data --name vol alpine:3.6 /bin/true
      #       docker cp 
      # - run: docker build -t build-container -f Dockerfile.build ./

      # - run: |
      #     docker run -it -v $(pwd)/pritunl:/pritunl \
      #                    -v $(pwd)/wheels:/wheels \
      #                    -w /pritunl build-container

      # - run: go get github.com/pritunl/pritunl-dns
      # - run: go get github.com/pritunl/pritunl-web
      # - run: pwd
      # - run: find /home
